### ISSUE TITLE
Useful R CMD envvars?

### ISSUE THREAD

**Issue by hadley** [MangoTheCat/callr#13]
Devtools has this:

```R
r_env_vars <- function() {
  vars <- c(
    "R_LIBS" = paste(.libPaths(), collapse = .Platform$path.sep),
    "CYGWIN" = "nodosfilewarning",
    # When R CMD check runs tests, it sets R_TESTS. When the tests
    # themselves run R CMD xxxx, as is the case with the tests in
    # devtools, having R_TESTS set causes errors because it confuses
    # the R subprocesses. Un-setting it here avoids those problems.
    "R_TESTS" = "",
    "R_BROWSER" = "false",
    "R_PDFVIEWER" = "false",
    "TAR" = auto_tar())

  if (is.na(Sys.getenv("NOT_CRAN", unset = NA))) {
    vars[["NOT_CRAN"]] <- "true"
  }

  vars
}

# Determine the best setting for the TAR environmental variable
# This is needed for R <= 2.15.2 to use internal tar. Later versions don't need
# this workaround, and they use R_BUILD_TAR instead of TAR, so this has no
# effect on them.
auto_tar <- function() {
  tar <- Sys.getenv("TAR", unset = NA)
  if (!is.na(tar)) return(tar)

  windows <- .Platform$OS.type == "windows"
  no_rtools <- is.null(get_rtools_path())
  if (windows && no_rtools) "internal" else ""
}
```

Would you consider adding to callr?

* I think you're probably already handling `R_LIBS`
* `auto_tar` can probably be dropped now

**Comment by gaborcsardi** [comment]
Hmmm. You can already pass env vars, and `.libPaths()` is also transferred,.

There is also `rcmd_safe()`, which does set most (all?) of these env vars:
```r
❯ callr::rcmd_safe
function (cmd, cmdargs = character(), libpath = .libPaths(),
    repos = c(getOption("repos"), c(CRAN = "https://cran.rstudio.com")),
    system_profile = FALSE, user_profile = FALSE, env = c(CYGWIN = "nodosfilewarning",
        R_TESTS = "", R_BROWSER = "false", R_PDFVIEWER = "false"), ...)
```

**Comment by hadley** [comment]
I guess the only thing that's missing is the `NOT_CRAN` env var. How would you feel about having callr set that? (I think it would be best in `rcmd`).  

It still might be worthwhile to pull out `c(CYGWIN = "nodosfilewarning", R_TESTS = "", R_BROWSER = "false", R_PDFVIEWER = "false")` into its own function so that you can easily add to the env vars set by `rcmd_safe()`

**Comment by gaborcsardi** [comment]
Yeah, I can add `NOT_CRAN`. I would add it to `rcmd_safe`, though. 

`rcmd` is "run this in a replica environment"

`rcmd_safe` is "run this in a safe environment"

Pulling it out is a good idea, too.

**Comment by hadley** [comment]
It might be worth documenting `rcmd` and `rcmd_safe` in the same file to make the connection more clear.

**Comment by hadley** [comment]
Also, why isn't safety the default? i.e. why isn't it (e.g.) `rcmd()` and `rcmd_unsafe()` (or maybe `rcmd_mimic()`)

**Comment by gaborcsardi** [comment]
Just question. Could be. 

At the time I wrote it, I needed the mimic behavior more than the safe one, especially for `r()`. 
Not that there are huge differences between `rcmd()` and `rcmd_safe()` currently....

But this is already on CRAN, so.... although I don't think many people use it.
