### ISSUE TITLE
Set repository

### ISSUE THREAD

**Issue by hadley** [MangoTheCat/callr#14]
Devtools has this:

```R
# Create a temporary .Rprofile based on the current "repos" option
# and return a named vector that corresponds to environment variables
# that need to be set to use this .Rprofile
r_profile <- function() {
  tmp_user_profile <- file.path(tempdir(), "Rprofile-devtools")
  tmp_user_profile_con <- file(tmp_user_profile, "w")
  on.exit(close(tmp_user_profile_con), add = TRUE)
  writeLines("options(repos =", tmp_user_profile_con)
  dput(getOption("repos"), tmp_user_profile_con)
  writeLines(")", tmp_user_profile_con)

  c(R_PROFILE_USER = tmp_user_profile)
}
```

To ensure that the repository from the current session gets carried over to the child. Would you consider this for callr?

**Comment by gaborcsardi** [comment]
I do copy over `getOption("repos")`, or whatever you specify. Isn't that enough?

**Comment by hadley** [comment]
How do you copy it over?

**Comment by gaborcsardi** [comment]
I create a temporary profile for it, and then point both `R_PROFILE` and `R_PROFILE_USER` to this temp profile.

**Comment by gaborcsardi** [comment]
The only case that does not work if both `user_profile` and `system_profile` are TRUE, but that is rare. We usually do not want the profiles, I think.

**Comment by hadley** [comment]
Ok, awesome :)
