### ISSUE TITLE
Option to print cmd used in rcmd()

### ISSUE THREAD

**Issue by hadley** [MangoTheCat/callr#15]
As well as `output = TRUE` it would be useful to have (say) `input = TRUE` which would print the complete command run by `rcmd()`.

**Comment by gaborcsardi** [comment]
`input` is misleading imo, at least it reminds me of `stdin`. So I would rather call it `echo`.

**Comment by hadley** [comment]
Agreed. For some reason I thought `stdout` was called `output`. I like `echo`
