### ISSUE TITLE
Installation failed: 'rcmd_safe_env' is not an exported object from 'namespace:callr' 

### ISSUE THREAD

**Issue by chrisaddy** [MangoTheCat/callr#17]
When installing packages via devtools::install_github("repository") I am receiving the error that `rcmd_safe_env' is not in the namespace of callr. I checked, and it looks like it is in fact in the namespace.

I am using Ubuntu, if that is helpful.

**Comment by gaborcsardi** [comment]
I suspect that this is because devtools uses callr to install callr. We'll need to work around this later.

As a workaround for now, you can use `remotes` to install it, see e.g. https://github.com/MangoTheCat/remotes#installation or just use the install script we provide:

```r
source("https://install-github.me/mangothecat/callr")
```

**Comment by gaborcsardi** [comment]
@chrisaddy did this solve the issue?

**Comment by chrisaddy** [comment]
Yes, like magic! Thank you.

**Comment by gaborcsardi** [comment]
No worries, and sorry for the trouble.

**Comment by sedzinfo** [comment]
The source did not solve my problem

**Comment by sedzinfo** [comment]
> install("psycholatefunctions")
Installing psycholatefunctions
Downloading GitHub repo hadley/ggplot2@master
from URL https://api.github.com/repos/hadley/ggplot2/zipball/master
Installing ggplot2
Downloading GitHub repo tidyverse/rlang@master
from URL https://api.github.com/repos/tidyverse/rlang/zipball/master
Installing rlang
Installation failed: NULL : 'rcmd_safe_env' is not an exported object from 'namespace:callr'
Downloading GitHub repo hadley/svglite@master
from URL https://api.github.com/repos/hadley/svglite/zipball/master
Installing svglite
trying URL 'https://cran.rstudio.com/src/contrib/gdtools_0.1.6.tar.gz'
Content type 'application/x-gzip' length 35263 bytes (34 KB)
==================================================
downloaded 34 KB

Installing gdtools
Downloading GitHub repo jimhester/withr@master
from URL https://api.github.com/repos/jimhester/withr/zipball/master
Installing withr
Installation failed: NULL : 'rcmd_safe_env' is not an exported object from 'namespace:callr'
Installation failed: NULL : 'rcmd_safe_env' is not an exported object from 'namespace:callr'
Downloading GitHub repo jimhester/withr@master
from URL https://api.github.com/repos/jimhester/withr/zipball/master
Skipping withr, it is already being installed.
Installation failed: NULL : 'rcmd_safe_env' is not an exported object from 'namespace:callr'
Downloading GitHub repo jimhester/withr@master
from URL https://api.github.com/repos/jimhester/withr/zipball/master
Skipping withr, it is already being installed.
Installation failed: NULL : 'rcmd_safe_env' is not an exported object from 'namespace:callr'
trying URL 'https://cran.rstudio.com/src/contrib/RcppArmadillo_0.7.960.1.2.tar.gz'
Content type 'application/x-gzip' length 1116748 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

Installing RcppArmadillo
Installation failed: NULL : 'rcmd_safe_env' is not an exported object from 'namespace:callr'
Downloading GitHub repo tidyverse/rlang@master
from URL https://api.github.com/repos/tidyverse/rlang/zipball/master
Skipping rlang, it is already being installed.
Error: 'rcmd_safe_env' is not an exported object from 'namespace:callr'

**Comment by sedzinfo** [comment]
install("psycholatefunctions")
Installing psycholatefunctions
Downloading GitHub repo hadley/ggplot2@master
from URL https://api.github.com/repos/hadley/ggplot2/zipball/master
Installing ggplot2
Downloading GitHub repo tidyverse/rlang@master
from URL https://api.github.com/repos/tidyverse/rlang/zipball/master
Installing rlang
Installation failed: NULL : 'rcmd_safe_env' is not an exported object from 'namespace:callr'
Downloading GitHub repo hadley/svglite@master
from URL https://api.github.com/repos/hadley/svglite/zipball/master
Installing svglite
trying URL 'https://cran.rstudio.com/src/contrib/gdtools_0.1.6.tar.gz'
Content type 'application/x-gzip' length 35263 bytes (34 KB)
==================================================
downloaded 34 KB

Installing gdtools
Downloading GitHub repo jimhester/withr@master
from URL https://api.github.com/repos/jimhester/withr/zipball/master
Installing withr
Installation failed: NULL : 'rcmd_safe_env' is not an exported object from 'namespace:callr'
Installation failed: NULL : 'rcmd_safe_env' is not an exported object from 'namespace:callr'
Downloading GitHub repo jimhester/withr@master
from URL https://api.github.com/repos/jimhester/withr/zipball/master
Skipping withr, it is already being installed.
Installation failed: NULL : 'rcmd_safe_env' is not an exported object from 'namespace:callr'
Downloading GitHub repo jimhester/withr@master
from URL https://api.github.com/repos/jimhester/withr/zipball/master
Skipping withr, it is already being installed.
Installation failed: NULL : 'rcmd_safe_env' is not an exported object from 'namespace:callr'
trying URL 'https://cran.rstudio.com/src/contrib/RcppArmadillo_0.7.960.1.2.tar.gz'
Content type 'application/x-gzip' length 1116748 bytes (1.1 MB)
==================================================
downloaded 1.1 MB

Installing RcppArmadillo
Installation failed: NULL : 'rcmd_safe_env' is not an exported object from 'namespace:callr'
Downloading GitHub repo tidyverse/rlang@master
from URL https://api.github.com/repos/tidyverse/rlang/zipball/master
Skipping rlang, it is already being installed.
Error: 'rcmd_safe_env' is not an exported object from 'namespace:callr'

**Comment by mojtaba-komeili** [comment]
I followed your solution (running script to install remote) on Mac and didn't work. Am I doing something wrong or is it different for Mac?

**Comment by Deleetdk** [comment]
Did not work for me either.

**Comment by jzadra** [comment]
Solution also did not work for me on mac

**Comment by chambox** [comment]
and also for me on ubuntu 16.04

**Comment by halflearned** [comment]
Having the same issue after updating from R 3.3.0 to 3.4.3.

**Comment by chambox** [comment]
For ubuntu 16.04 users, I realized a simple fix will be to update everything first so that your devtools and callr versions are up to date. Simply run the command 
`update.packages(ask = FALSE)​`

This solved everything for me
